# Generated by Django 4.2.16 on 2024-12-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Crash_Analysis", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="per_typ",
            field=models.PositiveSmallIntegerField(
                choices=[
                    ("1", "Driver of a Motor Vehicle In-Transport"),
                    ("2", "Passenger of a Motor Vehicle In-Transport"),
                    ("3", "Occupant of a Motor Vehicle Not In-Transport"),
                    ("4", "Occupant of a Non-Motor Vehicle Transport Device"),
                    ("5", "Pedestrian"),
                    ("6", "Bicyclist"),
                    ("7", "Other Pedalcyclist"),
                    ("8", "Person on Personal Conveyance"),
                    ("9", "Unknown Occupant Type in a Motor Vehicle In-Transport"),
                    ("10", "Person In/On a Building"),
                    ("19", "Unknown Type of Non-Motorist"),
                ],
                verbose_name="Person Type",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="sex",
            field=models.PositiveSmallIntegerField(
                choices=[
                    ("1", "Male"),
                    ("2", "Female"),
                    ("3", "Other"),
                    ("8", "Not Reported"),
                    ("9", "Unknown"),
                ],
                verbose_name="Sex/Gender",
            ),
        ),
    ]
